"""initial_schema

Revision ID: eee4a93e5213
Revises: 
Create Date: 2026-03-31 10:48:11.832164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eee4a93e5213'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscription_tier_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'DOCX', name='file_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'PARSED', 'SCORING', 'SCORED', 'OPTIMIZING', 'OPTIMIZED', 'ERROR', name='resume_status_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ats_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimized_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    op.create_index(op.f('ix_resumes_status'), 'resumes', ['status'], unique=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_table('resume_jobs',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=500), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('tailored_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_jobs_id'), 'resume_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_resume_jobs_resume_id'), 'resume_jobs', ['resume_id'], unique=False)
    op.create_table('resume_exports',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('format', sa.Enum('PDF', 'DOCX', name='export_format_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['resume_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_exports_id'), 'resume_exports', ['id'], unique=False)
    op.create_index(op.f('ix_resume_exports_job_id'), 'resume_exports', ['job_id'], unique=False)
    op.create_index(op.f('ix_resume_exports_resume_id'), 'resume_exports', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_exports_resume_id'), table_name='resume_exports')
    op.drop_index(op.f('ix_resume_exports_job_id'), table_name='resume_exports')
    op.drop_index(op.f('ix_resume_exports_id'), table_name='resume_exports')
    op.drop_table('resume_exports')
    op.drop_index(op.f('ix_resume_jobs_resume_id'), table_name='resume_jobs')
    op.drop_index(op.f('ix_resume_jobs_id'), table_name='resume_jobs')
    op.drop_table('resume_jobs')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
